########################### NETWORKS #################################
networks:
  default: 
    driver: bridge
######################################################################

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafanatest
    security_opt:
    - no-new-privileges:true
    restart: unless-stopped
    networks:
    - default
    ports:
    - "3015:3000"
    environment:
    - GF_USERS_DEFAULT_THEME=light

    user: $PUID
    volumes:
    - $DOCKERDIR/appdata/grafana:/var/lib/grafana
